# Generated by Django 5.2.12 on 2026-04-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='         ', max_length=9)),
                ('turn', models.CharField(default='X', max_length=1)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
    ]
