# Generated by Django 5.2.12 on 2026-04-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_created_at_game_finished_at_alter_game_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.CharField(default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
